### ISSUE TITLE
How to set a topic enhancement

### ISSUE THREAD

**Issue by Kun8018** [tidb-incubator/discourse-topic-enhancement#1]
![image](https://user-images.githubusercontent.com/41263766/129301982-973cf192-2e15-4e62-bd9a-390ccb3c7e3f.png)
I have install this plugin, and how to set a topic urgent?
Is this setting in topic?
I can  fill user guide if i can succeed

**Comment by hooopo** [comment]
这个你可以参考 但估计直接用是不行的 因为我们的discourse和在原版基础上做了很多改动
